# Used to build an artifact for Staging/Prod environments.
# See go/luci-config-deploy for further information.
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['source','repos', 'clone', 'dockerfiles', '--project=chrome-infra-spinnaker']
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--build-arg",  "directory=$_PROJECT_DIR",
      "-t", "gcr.io/chrome-infra-spinnaker/luci-config:latest",
      "-t", "gcr.io/chrome-infra-spinnaker/luci-config:$BUILD_ID",
      "./dockerfiles/infra-appengine"]
  - name: "gcr.io/cloud-builders/docker"
    args: ['run',
      '--volume', '/workspace:/workspace',
      'gcr.io/chrome-infra-spinnaker/luci-config',
      'make', 'package_release']
  - name: "gcr.io/chrome-infra-spinnaker/tar"
    args: ['cf', '$BUILD_ID.tar', '-C', 'package', '.']
artifacts:
  images: ["gcr.io/chrome-infra-spinnaker/luci-config"]
  objects:
    location: "gs://chrome-infra-builds/luci-config"
    paths:   ["$BUILD_ID.tar"]
